main: me.Liillemannen.BukkitServer.Main
name: LiillemannensEpicPlugin
version: 1.0.7
author: Liillemannen
api-version: 1.15

commands:
  Hello:
  Launch:
    aliases: lch
  Doctor:
    aliases: doc
  Refill:
    aliases: ref
  gm:
  GodBoots:
    aliases: gb
  Trident:
    aliases: tr
  ChangeTeam: