main: me.Liillemannen.BukkitServer.Main
name: LiillemannensEpicPlugin
version: 1.1.0
author: Liillemannen
api-version: 1.15

commands:
  Hello:
    description: just a hello world
  Launch:
    description: Launches you in the air
    aliases: lch
  Doctor:
    description: Heals you.
    aliases: doc
  Refill:
    description: Feeds you.
    aliases: ref
  gm:
    description: Allows you to change gamemode
  GodBoots:
    description: Gives you boots that have launch built into them.
    aliases: gb
  Trident:
    description: Gives you a trident that spawns drowned.
    aliases: tr
  ChangeTeam:
    description: Allows you to change team.
  setspawn:
    description: Sets spawn.
  Spawn:
    description: Teleports you to spawn.
  Sleep:
    description: Lets you change the sleep percentage.